[build]
  publish = "."  # Publish current directory
  command = ""   # No build command (it's a static site)

[[redirects]]
  from = "/*"
  to = "/comic.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"